spring.application.name=inventory-management
spring.datasource.url=jdbc:postgresql://localhost:5432/inventorydb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
file.upload-dir=./uploads/images


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kasgawadevyankatesh@gmail.com
spring.mail.password=iutx haol zhwy ivro
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.debug=true


# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=inventory_management_mongodb_db
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

razorpay.key_id=rzp_test_RUYSBS3A0kfC3w
razorpay.secret=5TnsqqFUm2HpZ4zBVJGyQwSl

